title: Кольца
email: your-email@domain.com
description: 'Кольца это лучшее в жизни! Свадьба это всегда кольца! Но кольца бывают разные. Чем больше кольца - тем лучше. Руки человека небольшие, и кольца на них тоже. Поэтому повесь кольца на машину! А лучше на КООООООРРРРРРТТТТТТЕЕЕЕЕЕЕЖЖЖЖ машин!'
baseurl: ''
url: 'https://www.kortezh63.ru'
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
  - kramdown
exclude:
  - config.ru
  - Gemfile
  - Gemfile.lock
  - vendor
  - Procfile
  - Rakefile